FROM node:22-alpine

WORKDIR /app/frontend

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

# Ensure vite is accessible from outside the container
CMD ["npm", "run", "dev", "--", "--host"]
