import React, { useEffect, useState } from 'react';
import { LoadingAnimation } from './LoadingAnimation';
import { CardiacMetrics } from './CardiacMetrics';
import { DiagnosisSection } from './DiagnosisSection';
import { Activity, Printer, Download } from 'lucide-react';
import { BullsEye } from './BullsEye';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { toast } from 'react-hot-toast';

interface AnalysisResult {
  ejectionFraction: number;
  simpsonEF: number;
  problem: string;
  cause: string;
  cure: string;
  gls: number;
  prognosticInsight: string;
  bullsEyeData: number[];
  edVolume: number;
  esVolume: number;
  index?: number;
  filename?: string;
}

interface ResultViewProps {
  inputVideos: (string | null)[];
  isProcessing: boolean;
  analysisResults: AnalysisResult[] | null;
}

export function ResultView({
  inputVideos,
  isProcessing,
  analysisResults
}: ResultViewProps) {
  const [maskGifs, setMaskGifs] = useState<(string | null)[]>([null, null]);
  const [ecgGifs, setEcgGifs] = useState<(string | null)[]>([null, null]);

  const handleReport = (result: AnalysisResult) => {
    try {
      const doc = new jsPDF();
      const timestamp = new Date().toLocaleString();

      // Header
      doc.setFontSize(22);
      doc.setTextColor(37, 99, 235);
      doc.text("CardioVision Clinical Report", 105, 20, { align: "center" });

      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(`Generated on: ${timestamp}`, 105, 28, { align: "center" });
      doc.text(`Sequence Index: ${result.index ?? 0} | Clinical Grade AI`, 105, 33, { align: "center" });

      doc.setDrawColor(226, 232, 240);
      doc.line(20, 40, 190, 40);

      // Section: Findings
      doc.setFontSize(12);
      doc.setTextColor(0);
      doc.setFont("helvetica", "bold");
      doc.text("Primary Diagnostic Findings:", 20, 50);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`Clinical Status: ${result.ejectionFraction < 45 ? 'Reduced EF (High Risk)' : 'Normal Cardiac Function'}`, 20, 58);

      // Metrics Table
      autoTable(doc, {
        startY: 65,
        head: [['Clinical Metric', 'Value', 'Reference Range']],
        body: [
          ['LVEF (Ejection Fraction)', `${result.ejectionFraction}%`, '50% - 70%'],
          ['GLS (Strain Analysis)', `${result.gls}%`, '< -18%'],
          ['ED Volume', `${result.edVolume} mL`, '60 - 150 mL'],
          ['ES Volume', `${result.esVolume} mL`, '20 - 60 mL'],
        ],
        theme: 'striped',
        headStyles: { fillColor: [37, 99, 235] }
      });

      // Diagnosis Section
      const finalY = (doc as any).lastAutoTable.finalY + 15;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text("Automated Diagnosis & Insights:", 20, finalY);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      const problemText = doc.splitTextToSize(`Finding: ${result.problem}`, 170);
      doc.text(problemText, 20, finalY + 8);

      const causeText = doc.splitTextToSize(`Etiology: ${result.cause}`, 170);
      doc.text(causeText, 20, finalY + 22);

      const cureText = doc.splitTextToSize(`Recommendation: ${result.cure}`, 170);
      doc.text(cureText, 20, finalY + 36);

      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text("This report is generated by AI and must be validated by a physician.", 105, 280, { align: "center" });

      doc.save(`Clinical_Report_${new Date().getTime()}.pdf`);
      toast.success("Clinical Report Generated");
    } catch (error) {
      console.error("PDF generation failed:", error);
      toast.error("Failed to generate PDF");
    }
  };

  const handlePrint = () => {
    window.print();
  };

  useEffect(() => {
    if (isProcessing) {
      maskGifs.forEach(url => url && URL.revokeObjectURL(url));
      ecgGifs.forEach(url => url && URL.revokeObjectURL(url));
      setMaskGifs([null, null]);
      setEcgGifs([null, null]);
      return;
    }

    if (!isProcessing && analysisResults) {
      const fetchResources = async () => {
        const newMasks = [...maskGifs];
        const newEcgs = [...ecgGifs];

        for (let i = 0; i < analysisResults.length; i++) {
          const res = analysisResults[i];
          const idx = res.index ?? i;
          try {
            // Fetch mask GIF
            const maskResponse = await fetch(`/api/ai/get-video/mask?index=${idx}`);
            if (maskResponse.ok) {
              const maskBlob = await maskResponse.blob();
              newMasks[idx] = URL.createObjectURL(maskBlob);
            }

            // Fetch ECG GIF
            const ecgResponse = await fetch(`/api/ai/get-video/ecg?index=${idx}`);
            if (ecgResponse.ok) {
              const ecgBlob = await ecgResponse.blob();
              newEcgs[idx] = URL.createObjectURL(ecgBlob);
            }
          } catch (error) {
            console.error(`Error fetching resources for index ${idx}:`, error);
          }
        }
        setMaskGifs(newMasks);
        setEcgGifs(newEcgs);
      };

      fetchResources();
    }

    return () => {
      maskGifs.forEach(url => url && URL.revokeObjectURL(url));
      ecgGifs.forEach(url => url && URL.revokeObjectURL(url));
    };
  }, [isProcessing, analysisResults]);

  if (isProcessing) {
    return (
      <div className="flex flex-col items-center justify-center p-20 glass-card">
        <LoadingAnimation />
        <p className="mt-8 text-xs font-black uppercase tracking-widest text-slate-500 animate-pulse">
          Concurrent Diagnostic Engine Running...
        </p>
      </div>
    );
  }

  if (!analysisResults) return null;

  const renderSingleResult = (result: AnalysisResult, index: number) => {
    const inputVideo = inputVideos[result.index ?? index];
    const maskGif = maskGifs[result.index ?? index];
    const ecgGif = ecgGifs[result.index ?? index];

    return (
      <div key={index} className="space-y-12 animate-fade-in py-8 border-b-2 border-slate-100 dark:border-white/5 last:border-0">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div className="flex items-center gap-4">
            <div className={`w-8 h-8 rounded-lg flex items-center justify-center text-white font-black text-xs ${index === 0 ? 'bg-blue-600' : 'bg-cyan-600'}`}>
              {index + 1}
            </div>
            <div>
              <h3 className="text-sm font-black uppercase tracking-widest text-slate-500">
                {index === 0 ? 'Baseline Assessment' : 'Follow-up Assessment'}
              </h3>
              <p className="text-[10px] text-slate-400 font-bold">Sequence ID: {result.filename || 'N/A'}</p>
            </div>
          </div>
          <div className="flex gap-3">
            <button
              onClick={() => handleReport(result)}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg text-[9px] font-black uppercase tracking-widest hover:bg-blue-500 transition-all"
            >
              Download PDF
            </button>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="space-y-3">
            <span className="text-[9px] font-black uppercase tracking-widest text-slate-400">Echo Sequence</span>
            <div className="relative aspect-video rounded-2xl overflow-hidden bg-black border border-white/5">
              {inputVideo && <video src={inputVideo} className="absolute inset-0 w-full h-full object-contain" autoPlay loop muted playsInline />}
            </div>
          </div>
          <div className="space-y-3">
            <span className="text-[9px] font-black uppercase tracking-widest text-slate-400">Segmentation Mask</span>
            <div className="relative aspect-video rounded-2xl overflow-hidden bg-cardio-darker/50 border border-white/5">
              {maskGif ? <img src={maskGif} className="absolute inset-0 w-full h-full object-contain" /> : <LoadingAnimation />}
            </div>
          </div>
          <div className="space-y-3">
            <span className="text-[9px] font-black uppercase tracking-widest text-slate-400">ECG Features</span>
            <div className="relative aspect-video rounded-2xl overflow-hidden bg-cardio-darker/50 border border-white/5">
              {ecgGif ? <img src={ecgGif} className="absolute inset-0 w-full h-full object-cover opacity-80" /> : <LoadingAnimation />}
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start mt-8">
          <div className="lg:col-span-5 space-y-8">
            <CardiacMetrics
              ejectionFraction={result.ejectionFraction}
              simpsonEF={result.simpsonEF}
              gls={result.gls}
              endDiastolicVolume={result.edVolume}
              endSystolicVolume={result.esVolume}
            />
          </div>

          <div className="lg:col-span-7">
            <BullsEye data={result.bullsEyeData} />
          </div>
        </div>

        <DiagnosisSection
          ejectionFraction={result.ejectionFraction}
          problem={result.problem}
          cause={result.cause}
          cure={result.cure}
          prognosticInsight={result.prognosticInsight}
        />
      </div>
    );
  };

  return (
    <div className="space-y-8">
      <div className="flex items-center justify-between no-print">
        <h2 className="text-2xl font-display font-black text-slate-900 dark:text-white tracking-tighter">
          Analysis <span className="text-blue-600">Results</span>
        </h2>
        <button
          onClick={handlePrint}
          className="flex items-center gap-2 px-6 py-2.5 bg-slate-100 dark:bg-white/5 text-slate-500 rounded-xl text-[10px] font-black uppercase tracking-widest border border-slate-200 dark:border-white/10 hover:bg-slate-200 transition-all no-print"
        >
          <Printer className="w-3.5 h-3.5" />
          Print Session
        </button>
      </div>

      <div className="space-y-16">
        {analysisResults.map((res, i) => renderSingleResult(res, i))}
      </div>
    </div>
  );
}
